resource_group_name = "cst8918-final-project-group-3-prod"
location            = "canadacentral"
cluster_name        = "group3-prod-aks"
dns_prefix          = "group3-prod-aks"
redis_name          = "group3-prod-redis"
