resource_group_name = "cst8918-final-project-group-3-test"
location            = "canadacentral"
cluster_name        = "group3-test-aks"
dns_prefix          = "group3-test-aks"
acr_name            = "group3acr"
redis_name          = "group3-test-redis"
