name: Application CI (Docker Build & Push)

on:
  push:
    branches: [main]
    paths:
      - 'app/**' # Triggered only when the content of the application folder changes
      - 'Dockerfile'

permissions:
  id-token: write # OIDC
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      ACR_NAME: ${{ vars.ACR_NAME }}
      IMAGE_NAME: remix-weather-app

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login to ACR
        run: |
          az acr login --name ${{ env.ACR_NAME }}

      - name: Build and Push Docker Image
        run: |
          FULL_IMAGE_NAME="${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}"

          echo "Building image: $FULL_IMAGE_NAME"

          docker build -t $FULL_IMAGE_NAME .

          docker push $FULL_IMAGE_NAME
