name: Terraform Static Analysis

on:
  push:
    branches: ["*"]
    paths:
      - "terraform/**"

permissions:
  contents: read

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check -recursive terraform/

      - name: Terraform Validate (dev)
        working-directory: terraform/environments/dev
        run: |
          terraform init -backend=false
          terraform validate

      - name: Terraform Validate (test)
        working-directory: terraform/environments/test
        run: |
          terraform init -backend=false
          terraform validate

      - name: Terraform Validate (prod)
        working-directory: terraform/environments/prod
        run: |
          terraform init -backend=false
          terraform validate

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          working_directory: terraform/
          soft_fail: true
